### ISSUE TITLE
Not calling chartFn

### ISSUE THREAD

**Issue by rdelrosario** [woodenconsulting/OpenCharts-For-Sencha-Touch-and-ExtJS#2]
I am trying this in a line chart but never gets called, so chart doesn't get formatted as expected.
My data is timestamps on the xAxis and a number represents distance on the yAxis.

chartFn: function(chart) {
                            chart.xScale = d3.time.scale();
                            chart.xAxis.axisLabel('Time (ms)').tickFormat(function(d) {
                                return d3.time.format('%x')(new Date(d));
                            });
                            chart.yAxis
                                .axisLabel('Activity')
                                .tickFormat(d3.format('.02f'));
},

**Comment by bertonoronha** [comment]
Hello there I am also using this incorporation of nvd3 with Sencha (which is great), and I am also facing this problem atm. Did you get any fix on this? I am trying to change the Chart code, but the problem seems to be in setting the chartFn variable.

Best,
Alberto

**Comment by camachoandres88** [comment]
I have the same problem, Could someone fix this problem?

**Comment by ERobishaw** [comment]
Found the fix!

The chartFn function is not getting sent to "applyChartProperties" function.

_In charts/Chart.js change the following two lines:_

```
        var chart = nv.models[this.getChartType()](),
            options = this.getChartOptions(),
            chartFn = this.getChartFn(),
            dom;
```

...

```
        this.applyChartProperties(chart, options, chartFn);
```
